development:
  adapter: postgresql
  encoding: unicode
  database: nuuz_development
  pool: 5
  username: nuuz
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: nuuz_test
  pool: 5
  username: nuuz
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: nuuz_production
  pool: 5
  username: nuuz
  password: